// Generated by tools/gen_trap_stubs.py — interrupt entry stubs for all 256 vectors.
// Each stub normalises the frame to (error code, vector) and joins trap_common,
// which saves every GPR, swaps to the kernel GS base if we came from ring 3,
// and calls trap_dispatch(&mut TrapFrame).
.section .text
.global trap_common
.global trap_stub_table

.align 16
trap_stub_0:
    push 0
    push 0
    jmp trap_common

.align 16
trap_stub_1:
    push 0
    push 1
    jmp trap_common

.align 16
trap_stub_2:
    push 0
    push 2
    jmp trap_common

.align 16
trap_stub_3:
    push 0
    push 3
    jmp trap_common

.align 16
trap_stub_4:
    push 0
    push 4
    jmp trap_common

.align 16
trap_stub_5:
    push 0
    push 5
    jmp trap_common

.align 16
trap_stub_6:
    push 0
    push 6
    jmp trap_common

.align 16
trap_stub_7:
    push 0
    push 7
    jmp trap_common

.align 16
trap_stub_8:
    push 8
    jmp trap_common

.align 16
trap_stub_9:
    push 0
    push 9
    jmp trap_common

.align 16
trap_stub_10:
    push 10
    jmp trap_common

.align 16
trap_stub_11:
    push 11
    jmp trap_common

.align 16
trap_stub_12:
    push 12
    jmp trap_common

.align 16
trap_stub_13:
    push 13
    jmp trap_common

.align 16
trap_stub_14:
    push 14
    jmp trap_common

.align 16
trap_stub_15:
    push 0
    push 15
    jmp trap_common

.align 16
trap_stub_16:
    push 0
    push 16
    jmp trap_common

.align 16
trap_stub_17:
    push 17
    jmp trap_common

.align 16
trap_stub_18:
    push 0
    push 18
    jmp trap_common

.align 16
trap_stub_19:
    push 0
    push 19
    jmp trap_common

.align 16
trap_stub_20:
    push 0
    push 20
    jmp trap_common

.align 16
trap_stub_21:
    push 21
    jmp trap_common

.align 16
trap_stub_22:
    push 0
    push 22
    jmp trap_common

.align 16
trap_stub_23:
    push 0
    push 23
    jmp trap_common

.align 16
trap_stub_24:
    push 0
    push 24
    jmp trap_common

.align 16
trap_stub_25:
    push 0
    push 25
    jmp trap_common

.align 16
trap_stub_26:
    push 0
    push 26
    jmp trap_common

.align 16
trap_stub_27:
    push 0
    push 27
    jmp trap_common

.align 16
trap_stub_28:
    push 0
    push 28
    jmp trap_common

.align 16
trap_stub_29:
    push 29
    jmp trap_common

.align 16
trap_stub_30:
    push 30
    jmp trap_common

.align 16
trap_stub_31:
    push 0
    push 31
    jmp trap_common

.align 16
trap_stub_32:
    push 0
    push 32
    jmp trap_common

.align 16
trap_stub_33:
    push 0
    push 33
    jmp trap_common

.align 16
trap_stub_34:
    push 0
    push 34
    jmp trap_common

.align 16
trap_stub_35:
    push 0
    push 35
    jmp trap_common

.align 16
trap_stub_36:
    push 0
    push 36
    jmp trap_common

.align 16
trap_stub_37:
    push 0
    push 37
    jmp trap_common

.align 16
trap_stub_38:
    push 0
    push 38
    jmp trap_common

.align 16
trap_stub_39:
    push 0
    push 39
    jmp trap_common

.align 16
trap_stub_40:
    push 0
    push 40
    jmp trap_common

.align 16
trap_stub_41:
    push 0
    push 41
    jmp trap_common

.align 16
trap_stub_42:
    push 0
    push 42
    jmp trap_common

.align 16
trap_stub_43:
    push 0
    push 43
    jmp trap_common

.align 16
trap_stub_44:
    push 0
    push 44
    jmp trap_common

.align 16
trap_stub_45:
    push 0
    push 45
    jmp trap_common

.align 16
trap_stub_46:
    push 0
    push 46
    jmp trap_common

.align 16
trap_stub_47:
    push 0
    push 47
    jmp trap_common

.align 16
trap_stub_48:
    push 0
    push 48
    jmp trap_common

.align 16
trap_stub_49:
    push 0
    push 49
    jmp trap_common

.align 16
trap_stub_50:
    push 0
    push 50
    jmp trap_common

.align 16
trap_stub_51:
    push 0
    push 51
    jmp trap_common

.align 16
trap_stub_52:
    push 0
    push 52
    jmp trap_common

.align 16
trap_stub_53:
    push 0
    push 53
    jmp trap_common

.align 16
trap_stub_54:
    push 0
    push 54
    jmp trap_common

.align 16
trap_stub_55:
    push 0
    push 55
    jmp trap_common

.align 16
trap_stub_56:
    push 0
    push 56
    jmp trap_common

.align 16
trap_stub_57:
    push 0
    push 57
    jmp trap_common

.align 16
trap_stub_58:
    push 0
    push 58
    jmp trap_common

.align 16
trap_stub_59:
    push 0
    push 59
    jmp trap_common

.align 16
trap_stub_60:
    push 0
    push 60
    jmp trap_common

.align 16
trap_stub_61:
    push 0
    push 61
    jmp trap_common

.align 16
trap_stub_62:
    push 0
    push 62
    jmp trap_common

.align 16
trap_stub_63:
    push 0
    push 63
    jmp trap_common

.align 16
trap_stub_64:
    push 0
    push 64
    jmp trap_common

.align 16
trap_stub_65:
    push 0
    push 65
    jmp trap_common

.align 16
trap_stub_66:
    push 0
    push 66
    jmp trap_common

.align 16
trap_stub_67:
    push 0
    push 67
    jmp trap_common

.align 16
trap_stub_68:
    push 0
    push 68
    jmp trap_common

.align 16
trap_stub_69:
    push 0
    push 69
    jmp trap_common

.align 16
trap_stub_70:
    push 0
    push 70
    jmp trap_common

.align 16
trap_stub_71:
    push 0
    push 71
    jmp trap_common

.align 16
trap_stub_72:
    push 0
    push 72
    jmp trap_common

.align 16
trap_stub_73:
    push 0
    push 73
    jmp trap_common

.align 16
trap_stub_74:
    push 0
    push 74
    jmp trap_common

.align 16
trap_stub_75:
    push 0
    push 75
    jmp trap_common

.align 16
trap_stub_76:
    push 0
    push 76
    jmp trap_common

.align 16
trap_stub_77:
    push 0
    push 77
    jmp trap_common

.align 16
trap_stub_78:
    push 0
    push 78
    jmp trap_common

.align 16
trap_stub_79:
    push 0
    push 79
    jmp trap_common

.align 16
trap_stub_80:
    push 0
    push 80
    jmp trap_common

.align 16
trap_stub_81:
    push 0
    push 81
    jmp trap_common

.align 16
trap_stub_82:
    push 0
    push 82
    jmp trap_common

.align 16
trap_stub_83:
    push 0
    push 83
    jmp trap_common

.align 16
trap_stub_84:
    push 0
    push 84
    jmp trap_common

.align 16
trap_stub_85:
    push 0
    push 85
    jmp trap_common

.align 16
trap_stub_86:
    push 0
    push 86
    jmp trap_common

.align 16
trap_stub_87:
    push 0
    push 87
    jmp trap_common

.align 16
trap_stub_88:
    push 0
    push 88
    jmp trap_common

.align 16
trap_stub_89:
    push 0
    push 89
    jmp trap_common

.align 16
trap_stub_90:
    push 0
    push 90
    jmp trap_common

.align 16
trap_stub_91:
    push 0
    push 91
    jmp trap_common

.align 16
trap_stub_92:
    push 0
    push 92
    jmp trap_common

.align 16
trap_stub_93:
    push 0
    push 93
    jmp trap_common

.align 16
trap_stub_94:
    push 0
    push 94
    jmp trap_common

.align 16
trap_stub_95:
    push 0
    push 95
    jmp trap_common

.align 16
trap_stub_96:
    push 0
    push 96
    jmp trap_common

.align 16
trap_stub_97:
    push 0
    push 97
    jmp trap_common

.align 16
trap_stub_98:
    push 0
    push 98
    jmp trap_common

.align 16
trap_stub_99:
    push 0
    push 99
    jmp trap_common

.align 16
trap_stub_100:
    push 0
    push 100
    jmp trap_common

.align 16
trap_stub_101:
    push 0
    push 101
    jmp trap_common

.align 16
trap_stub_102:
    push 0
    push 102
    jmp trap_common

.align 16
trap_stub_103:
    push 0
    push 103
    jmp trap_common

.align 16
trap_stub_104:
    push 0
    push 104
    jmp trap_common

.align 16
trap_stub_105:
    push 0
    push 105
    jmp trap_common

.align 16
trap_stub_106:
    push 0
    push 106
    jmp trap_common

.align 16
trap_stub_107:
    push 0
    push 107
    jmp trap_common

.align 16
trap_stub_108:
    push 0
    push 108
    jmp trap_common

.align 16
trap_stub_109:
    push 0
    push 109
    jmp trap_common

.align 16
trap_stub_110:
    push 0
    push 110
    jmp trap_common

.align 16
trap_stub_111:
    push 0
    push 111
    jmp trap_common

.align 16
trap_stub_112:
    push 0
    push 112
    jmp trap_common

.align 16
trap_stub_113:
    push 0
    push 113
    jmp trap_common

.align 16
trap_stub_114:
    push 0
    push 114
    jmp trap_common

.align 16
trap_stub_115:
    push 0
    push 115
    jmp trap_common

.align 16
trap_stub_116:
    push 0
    push 116
    jmp trap_common

.align 16
trap_stub_117:
    push 0
    push 117
    jmp trap_common

.align 16
trap_stub_118:
    push 0
    push 118
    jmp trap_common

.align 16
trap_stub_119:
    push 0
    push 119
    jmp trap_common

.align 16
trap_stub_120:
    push 0
    push 120
    jmp trap_common

.align 16
trap_stub_121:
    push 0
    push 121
    jmp trap_common

.align 16
trap_stub_122:
    push 0
    push 122
    jmp trap_common

.align 16
trap_stub_123:
    push 0
    push 123
    jmp trap_common

.align 16
trap_stub_124:
    push 0
    push 124
    jmp trap_common

.align 16
trap_stub_125:
    push 0
    push 125
    jmp trap_common

.align 16
trap_stub_126:
    push 0
    push 126
    jmp trap_common

.align 16
trap_stub_127:
    push 0
    push 127
    jmp trap_common

.align 16
trap_stub_128:
    push 0
    push 128
    jmp trap_common

.align 16
trap_stub_129:
    push 0
    push 129
    jmp trap_common

.align 16
trap_stub_130:
    push 0
    push 130
    jmp trap_common

.align 16
trap_stub_131:
    push 0
    push 131
    jmp trap_common

.align 16
trap_stub_132:
    push 0
    push 132
    jmp trap_common

.align 16
trap_stub_133:
    push 0
    push 133
    jmp trap_common

.align 16
trap_stub_134:
    push 0
    push 134
    jmp trap_common

.align 16
trap_stub_135:
    push 0
    push 135
    jmp trap_common

.align 16
trap_stub_136:
    push 0
    push 136
    jmp trap_common

.align 16
trap_stub_137:
    push 0
    push 137
    jmp trap_common

.align 16
trap_stub_138:
    push 0
    push 138
    jmp trap_common

.align 16
trap_stub_139:
    push 0
    push 139
    jmp trap_common

.align 16
trap_stub_140:
    push 0
    push 140
    jmp trap_common

.align 16
trap_stub_141:
    push 0
    push 141
    jmp trap_common

.align 16
trap_stub_142:
    push 0
    push 142
    jmp trap_common

.align 16
trap_stub_143:
    push 0
    push 143
    jmp trap_common

.align 16
trap_stub_144:
    push 0
    push 144
    jmp trap_common

.align 16
trap_stub_145:
    push 0
    push 145
    jmp trap_common

.align 16
trap_stub_146:
    push 0
    push 146
    jmp trap_common

.align 16
trap_stub_147:
    push 0
    push 147
    jmp trap_common

.align 16
trap_stub_148:
    push 0
    push 148
    jmp trap_common

.align 16
trap_stub_149:
    push 0
    push 149
    jmp trap_common

.align 16
trap_stub_150:
    push 0
    push 150
    jmp trap_common

.align 16
trap_stub_151:
    push 0
    push 151
    jmp trap_common

.align 16
trap_stub_152:
    push 0
    push 152
    jmp trap_common

.align 16
trap_stub_153:
    push 0
    push 153
    jmp trap_common

.align 16
trap_stub_154:
    push 0
    push 154
    jmp trap_common

.align 16
trap_stub_155:
    push 0
    push 155
    jmp trap_common

.align 16
trap_stub_156:
    push 0
    push 156
    jmp trap_common

.align 16
trap_stub_157:
    push 0
    push 157
    jmp trap_common

.align 16
trap_stub_158:
    push 0
    push 158
    jmp trap_common

.align 16
trap_stub_159:
    push 0
    push 159
    jmp trap_common

.align 16
trap_stub_160:
    push 0
    push 160
    jmp trap_common

.align 16
trap_stub_161:
    push 0
    push 161
    jmp trap_common

.align 16
trap_stub_162:
    push 0
    push 162
    jmp trap_common

.align 16
trap_stub_163:
    push 0
    push 163
    jmp trap_common

.align 16
trap_stub_164:
    push 0
    push 164
    jmp trap_common

.align 16
trap_stub_165:
    push 0
    push 165
    jmp trap_common

.align 16
trap_stub_166:
    push 0
    push 166
    jmp trap_common

.align 16
trap_stub_167:
    push 0
    push 167
    jmp trap_common

.align 16
trap_stub_168:
    push 0
    push 168
    jmp trap_common

.align 16
trap_stub_169:
    push 0
    push 169
    jmp trap_common

.align 16
trap_stub_170:
    push 0
    push 170
    jmp trap_common

.align 16
trap_stub_171:
    push 0
    push 171
    jmp trap_common

.align 16
trap_stub_172:
    push 0
    push 172
    jmp trap_common

.align 16
trap_stub_173:
    push 0
    push 173
    jmp trap_common

.align 16
trap_stub_174:
    push 0
    push 174
    jmp trap_common

.align 16
trap_stub_175:
    push 0
    push 175
    jmp trap_common

.align 16
trap_stub_176:
    push 0
    push 176
    jmp trap_common

.align 16
trap_stub_177:
    push 0
    push 177
    jmp trap_common

.align 16
trap_stub_178:
    push 0
    push 178
    jmp trap_common

.align 16
trap_stub_179:
    push 0
    push 179
    jmp trap_common

.align 16
trap_stub_180:
    push 0
    push 180
    jmp trap_common

.align 16
trap_stub_181:
    push 0
    push 181
    jmp trap_common

.align 16
trap_stub_182:
    push 0
    push 182
    jmp trap_common

.align 16
trap_stub_183:
    push 0
    push 183
    jmp trap_common

.align 16
trap_stub_184:
    push 0
    push 184
    jmp trap_common

.align 16
trap_stub_185:
    push 0
    push 185
    jmp trap_common

.align 16
trap_stub_186:
    push 0
    push 186
    jmp trap_common

.align 16
trap_stub_187:
    push 0
    push 187
    jmp trap_common

.align 16
trap_stub_188:
    push 0
    push 188
    jmp trap_common

.align 16
trap_stub_189:
    push 0
    push 189
    jmp trap_common

.align 16
trap_stub_190:
    push 0
    push 190
    jmp trap_common

.align 16
trap_stub_191:
    push 0
    push 191
    jmp trap_common

.align 16
trap_stub_192:
    push 0
    push 192
    jmp trap_common

.align 16
trap_stub_193:
    push 0
    push 193
    jmp trap_common

.align 16
trap_stub_194:
    push 0
    push 194
    jmp trap_common

.align 16
trap_stub_195:
    push 0
    push 195
    jmp trap_common

.align 16
trap_stub_196:
    push 0
    push 196
    jmp trap_common

.align 16
trap_stub_197:
    push 0
    push 197
    jmp trap_common

.align 16
trap_stub_198:
    push 0
    push 198
    jmp trap_common

.align 16
trap_stub_199:
    push 0
    push 199
    jmp trap_common

.align 16
trap_stub_200:
    push 0
    push 200
    jmp trap_common

.align 16
trap_stub_201:
    push 0
    push 201
    jmp trap_common

.align 16
trap_stub_202:
    push 0
    push 202
    jmp trap_common

.align 16
trap_stub_203:
    push 0
    push 203
    jmp trap_common

.align 16
trap_stub_204:
    push 0
    push 204
    jmp trap_common

.align 16
trap_stub_205:
    push 0
    push 205
    jmp trap_common

.align 16
trap_stub_206:
    push 0
    push 206
    jmp trap_common

.align 16
trap_stub_207:
    push 0
    push 207
    jmp trap_common

.align 16
trap_stub_208:
    push 0
    push 208
    jmp trap_common

.align 16
trap_stub_209:
    push 0
    push 209
    jmp trap_common

.align 16
trap_stub_210:
    push 0
    push 210
    jmp trap_common

.align 16
trap_stub_211:
    push 0
    push 211
    jmp trap_common

.align 16
trap_stub_212:
    push 0
    push 212
    jmp trap_common

.align 16
trap_stub_213:
    push 0
    push 213
    jmp trap_common

.align 16
trap_stub_214:
    push 0
    push 214
    jmp trap_common

.align 16
trap_stub_215:
    push 0
    push 215
    jmp trap_common

.align 16
trap_stub_216:
    push 0
    push 216
    jmp trap_common

.align 16
trap_stub_217:
    push 0
    push 217
    jmp trap_common

.align 16
trap_stub_218:
    push 0
    push 218
    jmp trap_common

.align 16
trap_stub_219:
    push 0
    push 219
    jmp trap_common

.align 16
trap_stub_220:
    push 0
    push 220
    jmp trap_common

.align 16
trap_stub_221:
    push 0
    push 221
    jmp trap_common

.align 16
trap_stub_222:
    push 0
    push 222
    jmp trap_common

.align 16
trap_stub_223:
    push 0
    push 223
    jmp trap_common

.align 16
trap_stub_224:
    push 0
    push 224
    jmp trap_common

.align 16
trap_stub_225:
    push 0
    push 225
    jmp trap_common

.align 16
trap_stub_226:
    push 0
    push 226
    jmp trap_common

.align 16
trap_stub_227:
    push 0
    push 227
    jmp trap_common

.align 16
trap_stub_228:
    push 0
    push 228
    jmp trap_common

.align 16
trap_stub_229:
    push 0
    push 229
    jmp trap_common

.align 16
trap_stub_230:
    push 0
    push 230
    jmp trap_common

.align 16
trap_stub_231:
    push 0
    push 231
    jmp trap_common

.align 16
trap_stub_232:
    push 0
    push 232
    jmp trap_common

.align 16
trap_stub_233:
    push 0
    push 233
    jmp trap_common

.align 16
trap_stub_234:
    push 0
    push 234
    jmp trap_common

.align 16
trap_stub_235:
    push 0
    push 235
    jmp trap_common

.align 16
trap_stub_236:
    push 0
    push 236
    jmp trap_common

.align 16
trap_stub_237:
    push 0
    push 237
    jmp trap_common

.align 16
trap_stub_238:
    push 0
    push 238
    jmp trap_common

.align 16
trap_stub_239:
    push 0
    push 239
    jmp trap_common

.align 16
trap_stub_240:
    push 0
    push 240
    jmp trap_common

.align 16
trap_stub_241:
    push 0
    push 241
    jmp trap_common

.align 16
trap_stub_242:
    push 0
    push 242
    jmp trap_common

.align 16
trap_stub_243:
    push 0
    push 243
    jmp trap_common

.align 16
trap_stub_244:
    push 0
    push 244
    jmp trap_common

.align 16
trap_stub_245:
    push 0
    push 245
    jmp trap_common

.align 16
trap_stub_246:
    push 0
    push 246
    jmp trap_common

.align 16
trap_stub_247:
    push 0
    push 247
    jmp trap_common

.align 16
trap_stub_248:
    push 0
    push 248
    jmp trap_common

.align 16
trap_stub_249:
    push 0
    push 249
    jmp trap_common

.align 16
trap_stub_250:
    push 0
    push 250
    jmp trap_common

.align 16
trap_stub_251:
    push 0
    push 251
    jmp trap_common

.align 16
trap_stub_252:
    push 0
    push 252
    jmp trap_common

.align 16
trap_stub_253:
    push 0
    push 253
    jmp trap_common

.align 16
trap_stub_254:
    push 0
    push 254
    jmp trap_common

.align 16
trap_stub_255:
    push 0
    push 255
    jmp trap_common

.align 16
trap_common:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15
    mov rax, [rsp + 15*8 + 3*8]
    test al, 3
    jz 1f
    swapgs
1:
    cld
    mov rdi, rsp
    call trap_dispatch
    mov rax, [rsp + 15*8 + 3*8]
    test al, 3
    jz 2f
    swapgs
2:
    pop r15
    pop r14
    pop r13
    pop r12
    pop r11
    pop r10
    pop r9
    pop r8
    pop rbp
    pop rdi
    pop rsi
    pop rdx
    pop rcx
    pop rbx
    pop rax
    add rsp, 16
    iretq

.section .rodata
.align 8
trap_stub_table:
    .quad trap_stub_0
    .quad trap_stub_1
    .quad trap_stub_2
    .quad trap_stub_3
    .quad trap_stub_4
    .quad trap_stub_5
    .quad trap_stub_6
    .quad trap_stub_7
    .quad trap_stub_8
    .quad trap_stub_9
    .quad trap_stub_10
    .quad trap_stub_11
    .quad trap_stub_12
    .quad trap_stub_13
    .quad trap_stub_14
    .quad trap_stub_15
    .quad trap_stub_16
    .quad trap_stub_17
    .quad trap_stub_18
    .quad trap_stub_19
    .quad trap_stub_20
    .quad trap_stub_21
    .quad trap_stub_22
    .quad trap_stub_23
    .quad trap_stub_24
    .quad trap_stub_25
    .quad trap_stub_26
    .quad trap_stub_27
    .quad trap_stub_28
    .quad trap_stub_29
    .quad trap_stub_30
    .quad trap_stub_31
    .quad trap_stub_32
    .quad trap_stub_33
    .quad trap_stub_34
    .quad trap_stub_35
    .quad trap_stub_36
    .quad trap_stub_37
    .quad trap_stub_38
    .quad trap_stub_39
    .quad trap_stub_40
    .quad trap_stub_41
    .quad trap_stub_42
    .quad trap_stub_43
    .quad trap_stub_44
    .quad trap_stub_45
    .quad trap_stub_46
    .quad trap_stub_47
    .quad trap_stub_48
    .quad trap_stub_49
    .quad trap_stub_50
    .quad trap_stub_51
    .quad trap_stub_52
    .quad trap_stub_53
    .quad trap_stub_54
    .quad trap_stub_55
    .quad trap_stub_56
    .quad trap_stub_57
    .quad trap_stub_58
    .quad trap_stub_59
    .quad trap_stub_60
    .quad trap_stub_61
    .quad trap_stub_62
    .quad trap_stub_63
    .quad trap_stub_64
    .quad trap_stub_65
    .quad trap_stub_66
    .quad trap_stub_67
    .quad trap_stub_68
    .quad trap_stub_69
    .quad trap_stub_70
    .quad trap_stub_71
    .quad trap_stub_72
    .quad trap_stub_73
    .quad trap_stub_74
    .quad trap_stub_75
    .quad trap_stub_76
    .quad trap_stub_77
    .quad trap_stub_78
    .quad trap_stub_79
    .quad trap_stub_80
    .quad trap_stub_81
    .quad trap_stub_82
    .quad trap_stub_83
    .quad trap_stub_84
    .quad trap_stub_85
    .quad trap_stub_86
    .quad trap_stub_87
    .quad trap_stub_88
    .quad trap_stub_89
    .quad trap_stub_90
    .quad trap_stub_91
    .quad trap_stub_92
    .quad trap_stub_93
    .quad trap_stub_94
    .quad trap_stub_95
    .quad trap_stub_96
    .quad trap_stub_97
    .quad trap_stub_98
    .quad trap_stub_99
    .quad trap_stub_100
    .quad trap_stub_101
    .quad trap_stub_102
    .quad trap_stub_103
    .quad trap_stub_104
    .quad trap_stub_105
    .quad trap_stub_106
    .quad trap_stub_107
    .quad trap_stub_108
    .quad trap_stub_109
    .quad trap_stub_110
    .quad trap_stub_111
    .quad trap_stub_112
    .quad trap_stub_113
    .quad trap_stub_114
    .quad trap_stub_115
    .quad trap_stub_116
    .quad trap_stub_117
    .quad trap_stub_118
    .quad trap_stub_119
    .quad trap_stub_120
    .quad trap_stub_121
    .quad trap_stub_122
    .quad trap_stub_123
    .quad trap_stub_124
    .quad trap_stub_125
    .quad trap_stub_126
    .quad trap_stub_127
    .quad trap_stub_128
    .quad trap_stub_129
    .quad trap_stub_130
    .quad trap_stub_131
    .quad trap_stub_132
    .quad trap_stub_133
    .quad trap_stub_134
    .quad trap_stub_135
    .quad trap_stub_136
    .quad trap_stub_137
    .quad trap_stub_138
    .quad trap_stub_139
    .quad trap_stub_140
    .quad trap_stub_141
    .quad trap_stub_142
    .quad trap_stub_143
    .quad trap_stub_144
    .quad trap_stub_145
    .quad trap_stub_146
    .quad trap_stub_147
    .quad trap_stub_148
    .quad trap_stub_149
    .quad trap_stub_150
    .quad trap_stub_151
    .quad trap_stub_152
    .quad trap_stub_153
    .quad trap_stub_154
    .quad trap_stub_155
    .quad trap_stub_156
    .quad trap_stub_157
    .quad trap_stub_158
    .quad trap_stub_159
    .quad trap_stub_160
    .quad trap_stub_161
    .quad trap_stub_162
    .quad trap_stub_163
    .quad trap_stub_164
    .quad trap_stub_165
    .quad trap_stub_166
    .quad trap_stub_167
    .quad trap_stub_168
    .quad trap_stub_169
    .quad trap_stub_170
    .quad trap_stub_171
    .quad trap_stub_172
    .quad trap_stub_173
    .quad trap_stub_174
    .quad trap_stub_175
    .quad trap_stub_176
    .quad trap_stub_177
    .quad trap_stub_178
    .quad trap_stub_179
    .quad trap_stub_180
    .quad trap_stub_181
    .quad trap_stub_182
    .quad trap_stub_183
    .quad trap_stub_184
    .quad trap_stub_185
    .quad trap_stub_186
    .quad trap_stub_187
    .quad trap_stub_188
    .quad trap_stub_189
    .quad trap_stub_190
    .quad trap_stub_191
    .quad trap_stub_192
    .quad trap_stub_193
    .quad trap_stub_194
    .quad trap_stub_195
    .quad trap_stub_196
    .quad trap_stub_197
    .quad trap_stub_198
    .quad trap_stub_199
    .quad trap_stub_200
    .quad trap_stub_201
    .quad trap_stub_202
    .quad trap_stub_203
    .quad trap_stub_204
    .quad trap_stub_205
    .quad trap_stub_206
    .quad trap_stub_207
    .quad trap_stub_208
    .quad trap_stub_209
    .quad trap_stub_210
    .quad trap_stub_211
    .quad trap_stub_212
    .quad trap_stub_213
    .quad trap_stub_214
    .quad trap_stub_215
    .quad trap_stub_216
    .quad trap_stub_217
    .quad trap_stub_218
    .quad trap_stub_219
    .quad trap_stub_220
    .quad trap_stub_221
    .quad trap_stub_222
    .quad trap_stub_223
    .quad trap_stub_224
    .quad trap_stub_225
    .quad trap_stub_226
    .quad trap_stub_227
    .quad trap_stub_228
    .quad trap_stub_229
    .quad trap_stub_230
    .quad trap_stub_231
    .quad trap_stub_232
    .quad trap_stub_233
    .quad trap_stub_234
    .quad trap_stub_235
    .quad trap_stub_236
    .quad trap_stub_237
    .quad trap_stub_238
    .quad trap_stub_239
    .quad trap_stub_240
    .quad trap_stub_241
    .quad trap_stub_242
    .quad trap_stub_243
    .quad trap_stub_244
    .quad trap_stub_245
    .quad trap_stub_246
    .quad trap_stub_247
    .quad trap_stub_248
    .quad trap_stub_249
    .quad trap_stub_250
    .quad trap_stub_251
    .quad trap_stub_252
    .quad trap_stub_253
    .quad trap_stub_254
    .quad trap_stub_255
